### PR TITLE
Add ability to read font through io.Reader

### PR DESCRIPTION
**Pull request by sivachandran**
Figure and Font are modified to read font data from io.Reader.

### CODE REVIEW

**Comment by lukeramsden** [comment]
+1 Super useful.

**Comment by common-nighthawk** [comment]
Sorry again for the long delay.  It'll be a nice improvement that users will able to create a Figure directly from any `flf` file.

I think it makes sense to maintain one point of entry to the program with `NewFigure`.  I think this helps with easy of use and reduces some code duplication.  Using the empty interface `empty interface` always feels like a poor hack, but what do you think of something like this?--

```
func NewFigure(phrase string, fontInfo interface{}, strict bool) figure {
  var font font
  switch fontInfo := fontInfo.(type) {
  case string:
    font = newFont(fontInfo)
  case io.Reader:
    font = newFontFromReader(fontInfo)
  }

  if font.reverse {
    phrase = reverse(phrase)
  }
  return figure{phrase, font, strict}
}
```

That way one new method is added to `Font` and then `NewFigure` knows which one to call by the type of the `fontInfo` argument.

**Comment by sivachandran** [comment]
@common-nighthawk I've never seen such pattern of `New` function accepting `interface{}` parameter and behaving differently based on the type of the param. It sounds like an anti-pattern of Go. Go always advocates for explicit naming of functions and parameters. Take `bytes.Buffer` for an example. It has two "New" functions, one that accepts byte array and another one accepts strings. They are specified explicitly. So it is better to keep the functions separately.

**Comment by common-nighthawk** [comment]
Hm.  I don't have enough experience with Go to have an informed decision.  I hate having two functions, but I recognize forcing everything in patterns I'm familiar with is terrible.

I'll go ahead and merge.  Do want to update the documentation?, or else I'll do it when I have a chance.

Thanks again for contributing and putting up with my response time.  I'm excited for this project to have more than one contributor 🎉

**Pull request merged**
